language: python
python:
  - "2.7"
cache: pip
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - sphinx-build -nW -b html -d _build/doctrees _docs _build/html
  - make publish github
before_script:
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${NICK}
after_script:
  - make purge